--- 离线重生模式
SkirmishMode = {}

local this = SkirmishMode

--- 初始化数据
this.initData = function()
    this.TeamAStartPoints = {}
    this.TeamBStartPoints = {}
    this.FriendBotVehicleList = {}
    this.EnemyBotVehicleList = {}
    this.TeamACount = 0
    this.TeamBCount = 0
    this.TeamAMaxNumber = 5
    this.TeamBMaxNumber = 5
    this.FriendScore = 0
    this.EnemyScore = 0
    this.customVehicleList = nil
    this.isPopEnd = false -- 防止结算界面重复出现
end

--- The view code is generated by tool automatically. Please do not modifiy it mannually.
this.initUI = function(root)
    --- @type GameObject
    this.vStartup = root:Find("#obj_Startup").gameObject
    --- @type InputField
    this.vFriendNumber = root:Find("#obj_Startup/Options/FriendNumber/#input_FriendNumber"):GetComponent("InputField")
    --- @type InputField
    this.vEnemyNumber = root:Find("#obj_Startup/Options/EnemyNumber/#input_EnemyNumber"):GetComponent("InputField")
    --- @type InputField
    this.vUpperRank = root:Find("#obj_Startup/Options/UpperRank/#input_UpperRank"):GetComponent("InputField")
    --- @type InputField
    this.vLowerRank = root:Find("#obj_Startup/Options/LowerRank/#input_LowerRank"):GetComponent("InputField")
    --- @type InputField
    this.vEnemyRankOffSet = root:Find("#obj_Startup/Options/EnemyRankOffSet/#input_EnemyRankOffSet"):GetComponent("InputField")
    --- @type InputField
    this.vMaxRandomPool = root:Find("#obj_Startup/Options/MaxRandomPool/#input_MaxRandomPool"):GetComponent("InputField")
    --- @type InputField
    this.vScoreToFinish = root:Find("#obj_Startup/Options/ScoreToFinish/#input_ScoreToFinish"):GetComponent("InputField")
    --- @type Button
    this.vCustomVehicleList = root:Find("#obj_Startup/Options/CustomVehicleList/#btn_CustomVehicleList"):GetComponent("Button")
    --- @type Button
    this.vStartBattle = root:Find("#obj_Startup/Options/StartBattle/#btn_StartBattle"):GetComponent("Button")
    --- @type Text
    this.vScore = root:Find("ScoreBar/#txt_Score"):GetComponent("Text")
    --- @type GameObject
    this.vFinishBar = root:Find("#obj_FinishBar").gameObject
    --- @type Text
    this.vWin = root:Find("#obj_FinishBar/#txt_Win"):GetComponent("Text")
    --- @type Text
    this.vLose = root:Find("#obj_FinishBar/#txt_Lose"):GetComponent("Text")
    --- @type Button
    this.vContinue = root:Find("#obj_FinishBar/#btn_Continue"):GetComponent("Button")
    --- @type Button
    this.vEnd = root:Find("#obj_FinishBar/#btn_End"):GetComponent("Button")
end


--- 初始化模式逻辑
this.initMode = function()
    -- 寻找出生点
    this.TeamAStartPoints = GameObject.FindGameObjectsWithTag("TeamAStartPoint")
    this.TeamBStartPoints = GameObject.FindGameObjectsWithTag("TeamBStartPoint")

    URPMainUIManager.Instance.audioListener.enabled = true -- 打开界面 Audio Listener 防止警告
    URPMainUIManager.Instance.selectVehicleBar:SetActive(true) -- 打开选车界面

    -- 结束战斗比分
    this.scoreToFinish = tonumber(this.vScoreToFinish.text)

    -- 设置敌我最大人数
    local firendNumber = tonumber(this.vFriendNumber.text)
    local enemyNumber = tonumber(this.vEnemyNumber.text)

    if GameDataManager.PlayerTeam == TeamManager.Team.red then
        this.TeamAMaxNumber = firendNumber
        this.TeamBMaxNumber = enemyNumber
    else
        this.TeamAMaxNumber = enemyNumber
        this.TeamBMaxNumber = firendNumber
    end

    -- 设置对战等级区间
    local lowerRank = tonumber(this.vLowerRank.text)
    local upperRank = tonumber(this.vUpperRank.text)

    local playerVehicle = VehicleInfoManager.Instance:GetVehicleInfo(URPCustomModeOfflineManager.PlayerVehicleName) -- 玩家的坦克
    local maxRandomPoolCount = tonumber(this.vMaxRandomPool.text) -- 坦克池，资源预热防止战斗卡顿，越大越吃内存

    -- 寻找合适的载具
    --- @type VehicleInfo[]
    local availableVehicleList = nil
    availableVehicleList = VehicleInfoManager.Instance:GetAllDriveableVehicleList():FindAll(
        function(x)
            return playerVehicle:GetRank() - lowerRank <= x:GetRank() and
                x:GetRank() <= playerVehicle:GetRank() + upperRank
        end
    )

    local enemyRank = playerVehicle:GetRank() + tonumber(this.vEnemyRankOffSet.text)

    local enemyAvailableVehicleList = nil
    enemyAvailableVehicleList = VehicleInfoManager.Instance:GetAllDriveableVehicleList():FindAll(
        function(x)
            return enemyRank - lowerRank <= x:GetRank() and x:GetRank() <= enemyRank + upperRank
        end
    )

    -- 通知创建载具列表
    URPMainUIManager.Instance:CreateVehicleUIs(playerVehicle, availableVehicleList)

    -- 载具选择后的回调
    URPMainUIManager.Instance.OnVehicleSelected:AddListener(
        function(vehicleInfo)
            URPMainUIManager.Instance.selectVehicleBar:SetActive(false)
            this.CreatePlayerVehicle(vehicleInfo)
        end
    )

    -- 载具被击毁的回调
    GameEventManager.OnNewVehicleDestroyed:AddListener(
        function(destroyedVehicle)
            --- Bot 被击毁，更新逻辑
            if Core.BaseInitSystem.IsLocalPlayer(destroyedVehicle._InstanceNetType) == false then
                if destroyedVehicle.ownerTeam == TeamManager.Team.red then
                    this.TeamACount = this.TeamACount - 1
                else
                    this.TeamBCount = this.TeamBCount - 1
                end
            end

            this.UpdateScore(destroyedVehicle)
            this.UpdateModeLogic()
        end
    )

    -- 载具物体清楚的回调
    GameEventManager.OnNewVehicleRemoved:AddListener(
        function(initSystem)
            --- 玩家死亡，显示选车界面
            if Core.BaseInitSystem.IsLocalPlayer(initSystem._InstanceNetType) then
                AudioListener.volume = 0

                URPMainUIManager.Instance.audioListener.enabled = true
                URPMainUIManager.Instance.backgroundCamera.enabled = true

                URPMainUIManager.Instance.selectVehicleBar:SetActive(true)
                MouseLockModule.Instance:OnVisible()
            end
        end
    )

    -- Bot 列表
    this.FriendBotVehicleList = CSharpAPI.GetBotVehicleList(availableVehicleList, maxRandomPoolCount)
    this.EnemyBotVehicleList = CSharpAPI.GetBotVehicleList(enemyAvailableVehicleList, maxRandomPoolCount)
    this.UpdateModeLogic()
end

this.onStartMode = function()
    this.initData()

    CSharpAPI.LoadAssetBundle(
        "LuaSkirmish",
        "mod",
        function(asset)
            if asset ~= nil then
                local go = GameObject.Instantiate(asset)
                this.instanceGo = go
                this.initUI(go.transform)

                this.vStartBattle.onClick:AddListener(
                    function()
                        this.vStartup:SetActive(false)
                        this.initMode()
                    end
                )

                this.vCustomVehicleList.onClick:AddListener(function()
                    UIManager.Instance:ShowUI(UIEnum.BANPICK_UI, function(ctrl)
                        this.customVehicleList = CSharpAPI.GetNewStringList()

                        ctrl:InitBanPickInfo(banList)
                        ctrl.onSaveCallBack:AddListener(function()
                            for k, v in pairs(this.customVehicleList) do
                                print(v)
                            end
                        end)
                    end)
                end)
            end
        end
    )
end

this.onExitMode = function()
end

--- Logic 战斗结束
--- @param isWin boolean 是否胜利
this.onBattleEnd = function(isWin)
    if not this.isPopEnd then
        Time.timeScale = 0

        this.vFinishBar:SetActive(true)

        if isWin then
            this.vWin:SetActive(true)
        else
            this.vLose:SetActive(true)
        end

        this.vContinue.onClick:AddListener(
            function()
                Time.timeScale = 1
                this.vFinishBar:SetActive(false)
            end
        )

        this.vEnd.onClick:AddListener(
            function()
                Time.timeScale = 1
                CSharpAPI.OnLuaExitModeReq:Invoke()
                GameObject.Destroy(this.instanceGo)
            end
        )
    end

    this.isPopEnd = true
end

--- 更新比分
this.UpdateScore = function(destroyedVehicle)
    local ownerTeam = destroyedVehicle.ownerTeam

    if ownerTeam == GameDataManager.PlayerTeam then
        this.EnemyScore = this.EnemyScore + 1
    else
        this.FriendScore = this.FriendScore + 1
    end

    this.vScore.text = tostring(this.FriendScore) .. ":" .. tostring(this.EnemyScore)

    -- 胜负条件
    if this.FriendScore >= this.scoreToFinish then
        this.onBattleEnd(true)
    end

    if this.EnemyScore >= this.scoreToFinish then
        this.onBattleEnd(false)
    end
end

--- 模式核心逻辑，循环遍历人数，补充缺失人数
this.UpdateModeLogic = function()
    if this.FriendBotVehicleList.Count ~= 0 and this.EnemyBotVehicleList.Count ~= 0 then
        if this.TeamACount < this.TeamAMaxNumber then
            local delta = this.TeamAMaxNumber - this.TeamACount - 1
            for i = 1, 1 + delta do
                this.TeamACount = this.TeamACount + 1
                this.CreateBotVehicle(TeamManager.Team.red)
            end
        end

        if this.TeamBCount < this.TeamBMaxNumber then
            local delta = this.TeamBMaxNumber - this.TeamBCount - 1
            for i = 1, 1 + delta do
                this.TeamBCount = this.TeamBCount + 1
                this.CreateBotVehicle(TeamManager.Team.blue)
            end
        end
    end
end

--- 创建玩家载具
--- @param vehicleInfo VehicleInfo
this.CreatePlayerVehicle = function(vehicleInfo)
    local startPoints = nil

    if GameDataManager.PlayerTeam == TeamManager.Team.red then
        startPoints = this.TeamAStartPoints
    else
        startPoints = this.TeamBStartPoints
    end

    URPCustomModeOfflineManager.Instance.respawnPointModule:RequestTrans(
        startPoints,
        function(trans)
            if vehicleInfo.type == VehicleInfo.Type.Ground then
                local tankInitSystem =
                CSharpAPI.CreateTankPlayer(vehicleInfo:GetVehicleName(), trans.position, trans.rotation)
                tankInitSystem.OnVehicleLoaded:AddListener(this.ClosePlayerUI)
            elseif vehicleInfo.type == VehicleInfo.Type.Aviation then
                local flightInitSystem =
                CSharpAPI.CreateFlightPlayer(vehicleInfo:GetVehicleName(), trans.position, trans.rotation, false)
                flightInitSystem.OnVehicleLoaded:AddListener(this.ClosePlayerUI)
            end
        end,
        0,
        true
    )
end

this.CreateBotVehicle = function(team)
    local startPoints = nil

    if team == TeamManager.Team.red then
        startPoints = this.TeamAStartPoints
    else
        startPoints = this.TeamBStartPoints
    end

    URPCustomModeOfflineManager.Instance.respawnPointModule:RequestTrans(
        startPoints,
        function(trans)
            local vehicleInfo = nil

            if team == GameDataManager.PlayerTeam then
                vehicleInfo = CSharpAPI.RandomVehicleFromList(this.FriendBotVehicleList)
            else
                vehicleInfo = CSharpAPI.RandomVehicleFromList(this.EnemyBotVehicleList)
            end

            if vehicleInfo.type == VehicleInfo.Type.Ground then
                CSharpAPI.CreateTankBot(vehicleInfo:GetVehicleName(), trans.position, trans.rotation, team)
            end
        end,
        0,
        true
    )
end

this.ClosePlayerUI = function()
    AudioListener.volume = 1
    URPMainUIManager.Instance.audioListener.enabled = false
    URPMainUIManager.Instance.backgroundCamera.enabled = false
    MouseLockModule.Instance:OnHide()
end
