---@class NetBattleView : BaseView
NetBattleView = class("NetBattleView", BaseView)

Lib()

local M = NetBattleView

-- Change M to your class name
function M:InitUI(root)
    -- The view code is generated by tool automatically. Please do not modifiy it mannually.
    --- @type GameObject
    self.vChat = root:Find("#obj_Chat").gameObject
    --- @type Button
    self.vOpenChatSender = root:Find("#obj_Chat/#btn_OpenChatSender"):GetComponent("Button")
    --- @type GameObject
    self.vChatMessages = root:Find("#obj_Chat/#obj_ChatMessages").gameObject
    --- @type GameObject
    self.vChatMessageTemplate = root:Find("#obj_Chat/#obj_ChatMessages/#obj_ChatMessageTemplate").gameObject
    --- @type GameObject
    self.vChatSenderBar = root:Find("#obj_Chat/#obj_ChatSenderBar").gameObject
    --- @type Button
    self.vCloseChatSenderBar = root:Find("#obj_Chat/#obj_ChatSenderBar/#btn_CloseChatSenderBar"):GetComponent("Button")
    --- @type InputField
    self.vSenderContent = root:Find("#obj_Chat/#obj_ChatSenderBar/#input_SenderContent"):GetComponent("InputField")
    --- @type Button
    self.vSendChat = root:Find("#obj_Chat/#obj_ChatSenderBar/#btn_SendChat"):GetComponent("Button")
    --- @type Dropdown
    self.vChatTargetType = root:Find("#obj_Chat/#obj_ChatSenderBar/#dropdown_ChatTargetType"):GetComponent("Dropdown")
    --- @type Text
    self.vPing = root:Find("#txt_Ping"):GetComponent("Text")
    --- @type GameObject
    self.vTextPopTemplate = root:Find("#obj_TextPopTemplate").gameObject
    --- @type Text
    self.vBattleMeta = root:Find("#txt_BattleMeta"):GetComponent("Text")
end
