---@class StandardWarView : BaseView
StandardWarView = class("StandardWarView", BaseView)

Lib()

local M = StandardWarView

-- Change M to your class name
function M:InitUI(root)
    -- The view code is generated by tool automatically. Please do not modifiy it mannually.
    --- @type GameObject
    self.vVehiclePickBar = root:Find("#obj_VehiclePickBar").gameObject
    --- @type Image
    self.vVehicleThumbnail = root:Find("#obj_VehiclePickBar/VehickeBackground'/#img_VehicleThumbnail"):GetComponent(
        typeof(Image))
    --- @type Text
    self.vVehicleName = root:Find("#obj_VehiclePickBar/VehickeBackground'/#img_VehicleThumbnail/#txt_VehicleName")
        :GetComponent(typeof(Text))
    --- @type Text
    self.vVehicleRank = root:Find("#obj_VehiclePickBar/VehickeBackground'/#img_VehicleThumbnail/#txt_VehicleRank")
        :GetComponent(typeof(Text))
    --- @type Button
    self.vPickVehicle = root:Find("#obj_VehiclePickBar/#btn_PickVehicle"):GetComponent(typeof(Button))
    --- @type Button
    self.vBattle = root:Find("#obj_VehiclePickBar/#btn_Battle"):GetComponent(typeof(Button))
    --- @type GameObject
    self.vUnuseMask = root:Find("#obj_VehiclePickBar/#btn_Battle/#obj_UnuseMask").gameObject
end
