AbstractNetBattleGameMode = CS.Frontend.Runtime.Impl.GameImpl.Battle.AbstractNetBattleGameMode
CaptureZoneNetGameMode = CS.Frontend.Runtime.Impl.GameImpl.Battle.Mode.CaptureZoneNetGameMode
ReplayNetGameMode = CS.Frontend.Runtime.Impl.GameImpl.Battle.Mode.ReplayNetGameMode
StandardWarNetGameMode = CS.Frontend.Runtime.Impl.GameImpl.Battle.Mode.StandardWarNetGameMode
TotalWarNetGameMode = CS.Frontend.Runtime.Impl.GameImpl.Battle.Mode.TotalWarNetGameMode
ZoneChain = CS.ShanghaiWindy.Data.ZoneChain
ZoneCapturePoint = CS.ShanghaiWindy.Data.ZoneCapturePoint
CaptureZone = CS.ShanghaiWindy.Data.CaptureZone
CaptureZoneModeConfig = CS.ShanghaiWindy.Data.CaptureZoneModeConfig
TransformInfo = CS.ShanghaiWindy.Data.TransformInfo
WaveAttackInfo = CS.ShanghaiWindy.Data.WaveAttackInfo
WaveInfo = CS.ShanghaiWindy.Data.WaveInfo
WaveMissionConfig = CS.ShanghaiWindy.Data.WaveMissionConfig
MaterialConfig = CS.ShanghaiWindy.Data.MaterialConfig
FlightPlayerState = CS.ShanghaiWindy.Core.FlightPlayerState
ObjectPoolComponent = CS.ShanghaiWindy.Core.ObjectPoolComponent
VehicleInfo = CS.ShanghaiWindy.Core.VehicleInfo
CaptureZoneTask = CS.ShanghaiWindy.Core.CaptureZoneTask
BaseFireSystem = CS.ShanghaiWindy.Core.BaseFireSystem
BaseInitSystem = CS.ShanghaiWindy.Core.BaseInitSystem
BasePawn = CS.ShanghaiWindy.Core.BasePawn
ECaptureStage = CS.ShanghaiWindy.Core.ECaptureStage
CaptureZoneInfo = CS.ShanghaiWindy.Core.CaptureZoneInfo
EIconPosition = CS.ShanghaiWindy.Core.EIconPosition
AbstractBattlePlayer = CS.ShanghaiWindy.Core.AbstractBattlePlayer
TeamManager = CS.ShanghaiWindy.Core.TeamManager
TankFire = CS.ShanghaiWindy.Core.TankFire
VehicleInitSystem = CS.ShanghaiWindy.Core.VehicleInitSystem
TankVehicleComponents = CS.ShanghaiWindy.Core.TankVehicleComponents
TurretController = CS.ShanghaiWindy.Core.TurretController
UIPoolComponent = CS.ShanghaiWindy.Core.UIPoolComponent
ILuaBase = CS.ShanghaiWindy.Core.Lua.ILuaBase
ILuaBehavior = CS.ShanghaiWindy.Core.Lua.ILuaBehavior
ILuaBuffCaster = CS.ShanghaiWindy.Core.Lua.ILuaBuffCaster
ILuaCommon = CS.ShanghaiWindy.Core.Lua.ILuaCommon
ILuaControllableVehicle = CS.ShanghaiWindy.Core.Lua.ILuaControllableVehicle
ILuaGameMode = CS.ShanghaiWindy.Core.Lua.ILuaGameMode
LuaBehaviorMono = CS.ShanghaiWindy.Core.Lua.LuaBehaviorMono
BulletFiredInfo = CS.ShanghaiWindy.Core.Data.BulletFiredInfo
InstantiateNonPoolObjectDelegate = CS.ShanghaiWindy.Core.Delegate.InstantiateNonPoolObjectDelegate
LoadPoolAssetDelegate = CS.ShanghaiWindy.Core.Delegate.LoadPoolAssetDelegate
OnGameVehicleLoadedDelegate = CS.ShanghaiWindy.Core.Delegate.OnGameVehicleLoadedDelegate
OnGameVehicleDestroyedDelegate = CS.ShanghaiWindy.Core.Delegate.OnGameVehicleDestroyedDelegate
OnGameVehicleGameObjectRemovedDelegate = CS.ShanghaiWindy.Core.Delegate.OnGameVehicleGameObjectRemovedDelegate
OnKeyPerformed = CS.ShanghaiWindy.Core.Delegate.OnKeyPerformed
OnKeyCanceled = CS.ShanghaiWindy.Core.Delegate.OnKeyCanceled
OnKeyRegistered = CS.ShanghaiWindy.Core.Delegate.OnKeyRegistered
OnKeyUnregistered = CS.ShanghaiWindy.Core.Delegate.OnKeyUnregistered
OnBattleSceneLoadedDelegate = CS.ShanghaiWindy.Core.Delegate.OnBattleSceneLoadedDelegate
OnBattleUILoadedDelegate = CS.ShanghaiWindy.Core.Delegate.OnBattleUILoadedDelegate
PostEventLoadedDelegate = CS.ShanghaiWindy.Core.Delegate.PostEventLoadedDelegate
OnQuarterTickDelegate = CS.ShanghaiWindy.Core.Delegate.OnQuarterTickDelegate
OnTickDelegate = CS.ShanghaiWindy.Core.Delegate.OnTickDelegate
OnVehicleLoadedDelegate = CS.ShanghaiWindy.Core.Delegate.OnVehicleLoadedDelegate
OnVehicleDestroyedDelegate = CS.ShanghaiWindy.Core.Delegate.OnVehicleDestroyedDelegate
OnVehicleRemovedDelegate = CS.ShanghaiWindy.Core.Delegate.OnVehicleRemovedDelegate
OnFiredDelegate = CS.ShanghaiWindy.Core.Delegate.OnFiredDelegate
OnVehicleThumbnailLoadedDelegate = CS.ShanghaiWindy.Core.Delegate.OnVehicleThumbnailLoadedDelegate
--- @class ShanghaiWindy.Core.API.ArmyAPI
ArmyAPI = CS.ShanghaiWindy.Core.API.ArmyAPI
--- @class ShanghaiWindy.Core.API.AssetAPI
AssetAPI = CS.ShanghaiWindy.Core.API.AssetAPI
--- @class ShanghaiWindy.Core.API.BattlePlayerAPI
BattlePlayerAPI = CS.ShanghaiWindy.Core.API.BattlePlayerAPI
--- @class ShanghaiWindy.Core.API.BotAPI
BotAPI = CS.ShanghaiWindy.Core.API.BotAPI
--- @class ShanghaiWindy.Core.API.BuffAPI
BuffAPI = CS.ShanghaiWindy.Core.API.BuffAPI
--- @class ShanghaiWindy.Core.API.CameraAPI
CameraAPI = CS.ShanghaiWindy.Core.API.CameraAPI
--- @class ShanghaiWindy.Core.API.CaptureZoneAPI
CaptureZoneAPI = CS.ShanghaiWindy.Core.API.CaptureZoneAPI
--- @class ShanghaiWindy.Core.API.ColorAPI
ColorAPI = CS.ShanghaiWindy.Core.API.ColorAPI
--- @class ShanghaiWindy.Core.API.ComponentAPI
ComponentAPI = CS.ShanghaiWindy.Core.API.ComponentAPI
--- @class ShanghaiWindy.Core.API.ConfigAPI
ConfigAPI = CS.ShanghaiWindy.Core.API.ConfigAPI
--- @class ShanghaiWindy.Core.API.ConvertAPI
ConvertAPI = CS.ShanghaiWindy.Core.API.ConvertAPI
--- @class ShanghaiWindy.Core.API.CustomOptionUIAPI
CustomOptionUIAPI = CS.ShanghaiWindy.Core.API.CustomOptionUIAPI
--- @class ShanghaiWindy.Core.API.FlightAPI
FlightAPI = CS.ShanghaiWindy.Core.API.FlightAPI
--- @class ShanghaiWindy.Core.API.FontAPI
FontAPI = CS.ShanghaiWindy.Core.API.FontAPI
--- @class ShanghaiWindy.Core.API.GameAPI
GameAPI = CS.ShanghaiWindy.Core.API.GameAPI
--- @class ShanghaiWindy.Core.API.GameObjectAPI
GameObjectAPI = CS.ShanghaiWindy.Core.API.GameObjectAPI
eDefaultValueInputType = CS.ShanghaiWindy.Core.API.eDefaultValueInputType
eDefaultButtonInputType = CS.ShanghaiWindy.Core.API.eDefaultButtonInputType
--- @class ShanghaiWindy.Core.API.InputAPI
InputAPI = CS.ShanghaiWindy.Core.API.InputAPI
--- @class ShanghaiWindy.Core.API.MapAPI
MapAPI = CS.ShanghaiWindy.Core.API.MapAPI
--- @class ShanghaiWindy.Core.API.MaterialAPI
MaterialAPI = CS.ShanghaiWindy.Core.API.MaterialAPI
--- @class ShanghaiWindy.Core.API.MeshAPI
MeshAPI = CS.ShanghaiWindy.Core.API.MeshAPI
--- @class ShanghaiWindy.Core.API.ModeAPI
ModeAPI = CS.ShanghaiWindy.Core.API.ModeAPI
--- @class ShanghaiWindy.Core.API.PointAPI
PointAPI = CS.ShanghaiWindy.Core.API.PointAPI
--- @class ShanghaiWindy.Core.API.RandomAPI
RandomAPI = CS.ShanghaiWindy.Core.API.RandomAPI
--- @class ShanghaiWindy.Core.API.SoundAPI
SoundAPI = CS.ShanghaiWindy.Core.API.SoundAPI
--- @class ShanghaiWindy.Core.API.SpawnAPI
SpawnAPI = CS.ShanghaiWindy.Core.API.SpawnAPI
--- @class ShanghaiWindy.Core.API.SpawnVehicleAPI
SpawnVehicleAPI = CS.ShanghaiWindy.Core.API.SpawnVehicleAPI
--- @class ShanghaiWindy.Core.API.StorageAPI
StorageAPI = CS.ShanghaiWindy.Core.API.StorageAPI
--- @class ShanghaiWindy.Core.API.TankAPI
TankAPI = CS.ShanghaiWindy.Core.API.TankAPI
--- @class ShanghaiWindy.Core.API.TeamAPI
TeamAPI = CS.ShanghaiWindy.Core.API.TeamAPI
--- @class ShanghaiWindy.Core.API.TimeAPI
TimeAPI = CS.ShanghaiWindy.Core.API.TimeAPI
--- @class ShanghaiWindy.Core.API.TransformAPI
TransformAPI = CS.ShanghaiWindy.Core.API.TransformAPI
--- @class ShanghaiWindy.Core.API.UIAPI
UIAPI = CS.ShanghaiWindy.Core.API.UIAPI
--- @class ShanghaiWindy.Core.API.VehicleAPI
VehicleAPI = CS.ShanghaiWindy.Core.API.VehicleAPI
IControllableVehicle = CS.ShanghaiWindy.Core.IControllableVehicle
UIEnum = CS.ShanghaiWindy.Core.UIEnum
