--- @class ShanghaiWindy.Core.API.ArmyAPI
ArmyAPI = CS.ShanghaiWindy.Core.API.ArmyAPI
--- @class ShanghaiWindy.Core.API.AssetAPI
AssetAPI = CS.ShanghaiWindy.Core.API.AssetAPI
--- @class ShanghaiWindy.Core.API.BattlePlayerAPI
BattlePlayerAPI = CS.ShanghaiWindy.Core.API.BattlePlayerAPI
--- @class ShanghaiWindy.Core.API.BuffAPI
BuffAPI = CS.ShanghaiWindy.Core.API.BuffAPI
--- @class ShanghaiWindy.Core.API.CameraAPI
CameraAPI = CS.ShanghaiWindy.Core.API.CameraAPI
--- @class ShanghaiWindy.Core.API.ComponentAPI
ComponentAPI = CS.ShanghaiWindy.Core.API.ComponentAPI
--- @class ShanghaiWindy.Core.API.ConfigAPI
ConfigAPI = CS.ShanghaiWindy.Core.API.ConfigAPI
--- @class ShanghaiWindy.Core.API.ConvertAPI
ConvertAPI = CS.ShanghaiWindy.Core.API.ConvertAPI
--- @class ShanghaiWindy.Core.API.CustomOptionUIAPI
CustomOptionUIAPI = CS.ShanghaiWindy.Core.API.CustomOptionUIAPI
--- @class ShanghaiWindy.Core.API.FlightAPI
FlightAPI = CS.ShanghaiWindy.Core.API.FlightAPI
--- @class ShanghaiWindy.Core.API.GameAPI
GameAPI = CS.ShanghaiWindy.Core.API.GameAPI
--- @class ShanghaiWindy.Core.API.InputAPI
InputAPI = CS.ShanghaiWindy.Core.API.InputAPI
--- @class ShanghaiWindy.Core.API.MapAPI
MapAPI = CS.ShanghaiWindy.Core.API.MapAPI
--- @class ShanghaiWindy.Core.API.MaterialAPI
MaterialAPI = CS.ShanghaiWindy.Core.API.MaterialAPI
--- @class ShanghaiWindy.Core.API.MeshAPI
MeshAPI = CS.ShanghaiWindy.Core.API.MeshAPI
--- @class ShanghaiWindy.Core.API.ModeAPI
ModeAPI = CS.ShanghaiWindy.Core.API.ModeAPI
--- @class ShanghaiWindy.Core.API.PointAPI
PointAPI = CS.ShanghaiWindy.Core.API.PointAPI
--- @class ShanghaiWindy.Core.API.RandomAPI
RandomAPI = CS.ShanghaiWindy.Core.API.RandomAPI
--- @class ShanghaiWindy.Core.API.SoundAPI
SoundAPI = CS.ShanghaiWindy.Core.API.SoundAPI
--- @class ShanghaiWindy.Core.API.SpawnAPI
SpawnAPI = CS.ShanghaiWindy.Core.API.SpawnAPI
--- @class ShanghaiWindy.Core.API.SpawnVehicleAPI
SpawnVehicleAPI = CS.ShanghaiWindy.Core.API.SpawnVehicleAPI
--- @class ShanghaiWindy.Core.API.StorageAPI
StorageAPI = CS.ShanghaiWindy.Core.API.StorageAPI
--- @class ShanghaiWindy.Core.API.TankAPI
TankAPI = CS.ShanghaiWindy.Core.API.TankAPI
--- @class ShanghaiWindy.Core.API.TeamAPI
TeamAPI = CS.ShanghaiWindy.Core.API.TeamAPI
--- @class ShanghaiWindy.Core.API.TransformAPI
TransformAPI = CS.ShanghaiWindy.Core.API.TransformAPI
--- @class ShanghaiWindy.Core.API.TriggerAPI
TriggerAPI = CS.ShanghaiWindy.Core.API.TriggerAPI
--- @class ShanghaiWindy.Core.API.UIAPI
UIAPI = CS.ShanghaiWindy.Core.API.UIAPI
--- @class ShanghaiWindy.Core.API.VehicleAPI
VehicleAPI = CS.ShanghaiWindy.Core.API.VehicleAPI
