---@class CaptureZoneView : BaseView
CaptureZoneView = class("CaptureZoneView", BaseView)

Lib()

local M = CaptureZoneView

-- Change M to your class name
function M:InitUI(root)
    -- The view code is generated by tool automatically. Please do not modifiy it mannually.
    --- @type GameObject
    self.vCapturePickBar = root:Find("#obj_CapturePickBar").gameObject
    --- @type GameObject
    self.vPointTemplate = root:Find("#obj_CapturePickBar/#obj_PointTemplate").gameObject
    --- @type Image
    self.vVehicleThumbnail = root:Find("#obj_CapturePickBar/#img_VehicleThumbnail"):GetComponent("Image")
    --- @type Button
    self.vPickVehicle = root:Find("#obj_CapturePickBar/#btn_PickVehicle"):GetComponent("Button")
end
