---@class CaptureZoneView : BaseView
CaptureZoneView = class("CaptureZoneView", BaseView)

Lib()

local M = CaptureZoneView

-- Change M to your class name
function M:InitUI(root)
    -- The view code is generated by tool automatically. Please do not modifiy it mannually.
    --- @type GameObject
    self.vCapturePickBar = root:Find("#obj_CapturePickBar").gameObject
    --- @type Image
    self.vVehicleThumbnail = root:Find("#obj_CapturePickBar/#img_VehicleThumbnail"):GetComponent("Image")
    --- @type Text
    self.vVehicleName = root:Find("#obj_CapturePickBar/#img_VehicleThumbnail/#txt_VehicleName"):GetComponent("Text")
    --- @type Text
    self.vVehicleRank = root:Find("#obj_CapturePickBar/#img_VehicleThumbnail/#txt_VehicleRank"):GetComponent("Text")
    --- @type Button
    self.vPickVehicle = root:Find("#obj_CapturePickBar/#btn_PickVehicle"):GetComponent("Button")
    --- @type Button
    self.vBattle = root:Find("#obj_CapturePickBar/#btn_Battle"):GetComponent("Button")
    --- @type GameObject
    self.vPointTemplate = root:Find("#obj_PointTemplate").gameObject
end
