---@class ScreenShotView : BaseView
ScreenShotView = class("ScreenShotView", BaseView)

Lib()

local M = ScreenShotView

-- Change M to your class name
function M:InitUI(root)
    -- The view code is generated by tool automatically. Please do not modifiy it mannually.
    self.root = root
    --- @type Button
    self.vScreenShot = root:Find("Panel/#btn_ScreenShot"):GetComponent("Button")
end
