---@class NetReportReplayView : BaseView
NetReportReplayView = class("NetReportReplayView", BaseView)

Lib()

local M = NetReportReplayView

-- Change M to your class name
function M:InitUI(root)
    -- The view code is generated by tool automatically. Please do not modifiy it mannually.
    --- @type Text
    self.vNickName = root:Find("#txt_NickName"):GetComponent("Text")
    --- @type Button
    self.vAgreeBan = root:Find("ActionBar/#btn_AgreeBan"):GetComponent("Button")
    --- @type Button
    self.vDisagreeBan = root:Find("ActionBar/#btn_DisagreeBan"):GetComponent("Button")
    --- @type Button
    self.vBan = root:Find("ActionBar/#btn_Ban"):GetComponent("Button")
end
